version: "3.9"

services:
  web:
    build: ./web
    container_name: desafio3_web
    depends_on:
      - db
      - cache
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      REDIS_HOST: cache
    networks:
      - internal_net

  db:
    image: postgres:14
    container_name: desafio3_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal_net

  cache:
    image: redis:7
    container_name: desafio3_cache
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge
